# Generated by Django 2.2.5 on 2020-07-09 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200710_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Facilities',
            new_name='facilities',
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
